@AuthAPI_HostAddress = http://localhost:5176/api/Autenticate
POST {{AuthAPI_HostAddress}}/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "giga222@gmail.com",
    "password": "@"
}

###

POST {{AuthAPI_HostAddress}}/register-admin
Content-Type: application/json

{
    "username": "testadmin",
    "email": "giga@gmail.com",
    "password": "@"
}

###

POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
    "username": "testuser"
    "password": "@"
}

###