@StoreAPI_HostAddress = http://localhost:5176/api
@Store_AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdHVzZXIiLCJqdGkiOiJjNDdiMjk0My1jMzQwLTQ1ZmYtYjgwNS1jZjA0MDg0NDc2NzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzY3NTM2OTkwLCJpc3MiOiIqIiwiYXVkIjoiKiJ9.OQh0Bd8ocOh6VTBRIZzZO05m7T5Wg9NoGc2f8rzjQ0o

//Test Connect Database
GET {{StoreAPI_HostAddress}}/Product/testconnectdb
Accept: application/json
Authorization: Bearer {{Store_AccessToken}}

###

GET  {{StoreAPI_HostAddress}}/Product
Accept: application/json
Authorization: Bearer {{Store_AccessToken}}

###

GET  {{StoreAPI_HostAddress}}/Product/2
Accept: application/json

###

POST {{StoreAPI_HostAddress}}/Product
Accept: application/json
Authorization: Bearer {{Store_AccessToken}}

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW 

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="category_id" 
2

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="product_name" 
"Mobile Product New 2024"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_price" 
10

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="unit_in_stock" 
100

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; 

filename="iphone.png" 
Content-Type: image/png 

< ./sample_images/iphone.png 
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
PUT {{StoreAPI_HostAddress}}/Product/5
Accept: application/json
Content-Type: application/json


###
DELETE {{StoreAPI_HostAddress}}/Product/5
Accept: application/json
Content-Type: application/json